version: '3'

services:
  ssbc:
    build: .
    ports:
      - 50080:80
      - 1935:1935
    volumes:
      - ./volumes/ssbc/access_log:/var/log/nginx
      - ./volumes/ssbc/hls:/usr/local/nginx/html
